INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Ahsan', 'Get AWS Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Ahsan', 'Get Spring Boot Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Ahsan', 'Get Java Certified', CURRENT_DATE, false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Ahsan', 'Get Cycling Certified', CURRENT_DATE, false);
